### ISSUE TITLE
Fails to build on macOS 

### ISSUE THREAD

**Issue by eddyc** [nwhetsell/linter-csound#1]
Hi,

I've tried installing this on macOS and I'm getting the following error

```
> csound-api@0.9.4 install /private/var/folders/cm/q771w6n95sb788rjgk5jmmlr0000gn/T/apm-install-dir-11709-25043-mupu4u/node_modules/linter-csound/node_modules/csound-api
> node-gyp rebuild

  CXX(target) Release/obj.target/csound-api/src/csound-api.o

2017-01-09 18:16:19.604 xcodebuild[25056:1490285] [MT] PluginLoading: Required plug-in compatibility UUID E0A62D1F-3C18-4D74-BFE5-A4167D643966 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/JumpMarks.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2017-01-09 18:16:19.604 xcodebuild[25056:1490285] [MT] PluginLoading: Required plug-in compatibility UUID E0A62D1F-3C18-4D74-BFE5-A4167D643966 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2017-01-09 18:16:19.754 xcodebuild[25056:1490285] WARNING: Failed to load plugin at path: "/Users/eddyc/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim.xcplugin", skipping. Error: Error Domain=NSCocoaErrorDomain Code=3587 "dlopen_preflight(/Users/eddyc/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim.xcplugin/Contents/MacOS/XVim): no suitable image found.  Did find:
	/Users/eddyc/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim.xcplugin/Contents/MacOS/XVim: code signing blocked mmap() of '/Users/eddyc/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim.xcplugin/Contents/MacOS/XVim'" UserInfo={NSLocalizedFailureReason=The bundle is damaged or missing necessary resources., NSLocalizedRecoverySuggestion=Try reinstalling the bundle., NSFilePath=/Users/eddyc/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim.xcplugin/Contents/MacOS/XVim, NSDebugDescription=dlopen_preflight(/Users/eddyc/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim.xcplugin/Contents/MacOS/XVim): no suitable image found.  Did find:
	/Users/eddyc/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim.xcplugin/Contents/MacOS/XVim: code signing blocked mmap() of '/Users/eddyc/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim.xcplugin/Contents/MacOS/XVim', NSBundlePath=/Users/eddyc/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XVim.xcplugin, NSLocalizedDescription=The bundle “XVim” couldn’t be loaded because it is damaged or missing necessary resources.}
../src/csound-api.cc:2:10: fatal error: 'csound/cwindow.h' file not found
#include <csound/cwindow.h>
         ^
1 error generated.
make: *** [Release/obj.target/csound-api/src/csound-api.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 16.3.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /private/var/folders/cm/q771w6n95sb788rjgk5jmmlr0000gn/T/apm-install-dir-11709-25043-mupu4u/node_modules/linter-csound/node_modules/csound-api
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/cm/q771w6n95sb788rjgk5jmmlr0000gn/T/apm-install-dir-11709-25043-mupu4u/package.json'
npm WARN apm-install-dir-11709-25043-mupu4u No description
npm WARN apm-install-dir-11709-25043-mupu4u No repository field.
npm WARN apm-install-dir-11709-25043-mupu4u No README data
npm WARN apm-install-dir-11709-25043-mupu4u No license field.
npm ERR! Darwin 16.3.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/eddyc/.atom/.apm/.apmrc" "--userconfig" "/Users/eddyc/.atom/.apmrc" "install" "/private/var/folders/cm/q771w6n95sb788rjgk5jmmlr0000gn/T/d-11709-25043-1clc7wj/package.tgz" "--runtime=electron" "--target=1.3.13" "--arch=x64" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! csound-api@0.9.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the csound-api@0.9.4 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the csound-api package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs csound-api
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls csound-api
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/cm/q771w6n95sb788rjgk5jmmlr0000gn/T/apm-install-dir-11709-25043-mupu4u/npm-debug.log
```

Seems it can't find cwindow.h, I am building csound myself and the framework is installed to ~/Library/Frameworks, I think in the standard installation it is installed to /Library/Frameworks which may be an issue. This appears to be a problem with csound-api actually.

Update:

OK, so I was able to fix it using sudo ln -s ~/Library/Frameworks/CsoundLib64.framework/Headers /usr/local/include/csound

**Comment by nwhetsell** [comment]
Excellent! That’s exactly what I was about to suggest.
