### ISSUE TITLE
Install failed on Windows trying to build csound-api

### ISSUE THREAD

**Issue by bellicapax** [nwhetsell/linter-csound#11]
When I try to install via Atom, it gives me an error. This bit seems to be the relevant part and the first part that fails:

```
116 silly install csound-api@0.10.10
117 info lifecycle csound-api@0.10.10~install: csound-api@0.10.10
118 verbose lifecycle csound-api@0.10.10~install: unsafe-perm in lifecycle true
119 verbose lifecycle csound-api@0.10.10~install: PATH: C:\Users\erisk\AppData\Local\atom\app-1.35.1\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\erisk\AppData\Local\Temp\apm-install-dir-119216-10664-1ja5n0g.k9as\node_modules\linter-csound\node_modules\csound-api\node_modules\.bin;C:\Users\erisk\AppData\Local\Temp\apm-install-dir-119216-10664-1ja5n0g.k9as\node_modules\linter-csound\node_modules\.bin;C:\Users\erisk\AppData\Local\Temp\apm-install-dir-119216-10664-1ja5n0g.k9as\node_modules\.bin;C:\Users\erisk\AppData\Local\atom\app-1.35.1\resources\app\apm\bin; [OMITTED]
120 verbose lifecycle csound-api@0.10.10~install: CWD: C:\Users\erisk\AppData\Local\Temp\apm-install-dir-119216-10664-1ja5n0g.k9as\node_modules\linter-csound\node_modules\csound-api
121 silly lifecycle csound-api@0.10.10~install: Args: [ '/d /s /c', 'node-gyp rebuild' ]
122 silly lifecycle csound-api@0.10.10~install: Returned: code: 1  signal: null
123 info lifecycle csound-api@0.10.10~install: Failed to exec install script
124 timing action:install Completed in 11045ms
125 verbose unlock done using C:\Users\erisk\.atom\.apm\_locks\staging-f7c9df147eca2733.lock for C:\Users\erisk\AppData\Local\Temp\apm-install-dir-119216-10664-1ja5n0g.k9as\node_modules\.staging
126 timing stage:rollbackFailedOptional Completed in 248ms
127 timing stage:runTopLevelLifecycles Completed in 17337ms
128 silly saveTree apm-install-dir-119216-10664-1ja5n0g.k9as
128 silly saveTree `-- linter-csound@0.5.5
128 silly saveTree   `-- csound-api@0.10.10
128 silly saveTree     `-- nan@2.13.1
129 warn enoent ENOENT: no such file or directory, open 'C:\Users\erisk\AppData\Local\Temp\apm-install-dir-119216-10664-1ja5n0g.k9as\package.json'
130 verbose enoent This is related to npm not being able to find a file.
131 warn apm-install-dir-119216-10664-1ja5n0g.k9as No description
132 warn apm-install-dir-119216-10664-1ja5n0g.k9as No repository field.
133 warn apm-install-dir-119216-10664-1ja5n0g.k9as No README data
134 warn apm-install-dir-119216-10664-1ja5n0g.k9as No license field.
135 verbose stack Error: csound-api@0.10.10 install: `node-gyp rebuild`
135 verbose stack Exit status 1
135 verbose stack     at EventEmitter.<anonymous> (C:\Users\erisk\AppData\Local\atom\app-1.35.1\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\index.js:304:16)
135 verbose stack     at emitTwo (events.js:126:13)
135 verbose stack     at EventEmitter.emit (events.js:214:7)
135 verbose stack     at ChildProcess.<anonymous> (C:\Users\erisk\AppData\Local\atom\app-1.35.1\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
135 verbose stack     at emitTwo (events.js:126:13)
135 verbose stack     at ChildProcess.emit (events.js:214:7)
135 verbose stack     at maybeClose (internal/child_process.js:925:16)
135 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
136 verbose pkgid csound-api@0.10.10
137 verbose cwd C:\Users\erisk\AppData\Local\Temp\apm-install-dir-119216-10664-1ja5n0g.k9as
138 verbose Windows_NT 10.0.17134
139 verbose argv "C:\\Users\\erisk\\AppData\\Local\\atom\\app-1.35.1\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\erisk\\AppData\\Local\\atom\\app-1.35.1\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\erisk\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\erisk\\.atom\\.apmrc" "install" "https://www.atom.io/api/packages/linter-csound/versions/0.5.5/tarball" "--runtime=electron" "--target=2.0.18" "--dist-url=https://atom.io/download/electron" "--arch=x64" "--global-style" "--msvs_version=2015"
140 verbose node v8.9.3
141 verbose npm  v6.2.0
142 error code ELIFECYCLE
143 error errno 1
144 error csound-api@0.10.10 install: `node-gyp rebuild`
144 error Exit status 1
145 error Failed at the csound-api@0.10.10 install script.
145 error This is probably not a problem with npm. There is likely additional logging output above.
146 verbose exit [ 1, true ]
```

Any help is appreciated! I do have csound already installed and working prior to this.

**Comment by nwhetsell** [comment]
This is weird. Can you:

1. Quit Atom.

2. Run in PowerShell:

    ```powershell
    $Env:CL = "/I`"C:\local\boost_1_69_0`" /I`"$Env:ProgramFiles\Csound6_x64\include`""
    $Env:LINK = "`"$Env:ProgramFiles\Csound6_x64\lib\csound64.lib`""
    apm install linter-csound
    Set-Location $Env:USERPROFILE\.atom\packages\linter-csound
    apm rebuild csound-api
    ```

    or in Command Prompt:

    ```batch
    set CL=/I"C:\local\boost_1_69_0" /I"%ProgramFiles%\Csound6_x64\include"
    set LINK="%ProgramFiles%\Csound6_x64\lib\csound64.lib"
    apm install linter-csound
    cd %USERPROFILE%\.atom\packages\linter-csound
    apm rebuild csound-api
    ```

    (You may need to replace `C:\local\boost_1_69_0`, and `$Env:ProgramFiles\Csound6_x64` or `%ProgramFiles%\Csound6_x64`, with the paths of Boost and Csound on your computer.)

3. Restart Atom.

Does linter-csound seem to work, or does Atom show errors about incompatible packages (there may be a red bug icon in the status bar at the bottom of the Atom window) and ask you to rebuild them?

For what it's worth, tests of both [linter-csound](https://ci.appveyor.com/project/nwhetsell/linter-csound/builds/23129973) and [csound-api](https://ci.appveyor.com/project/nwhetsell/csound-api/builds/23129957) are passing on AppVeyor.

**Comment by bellicapax** [comment]
Linter-csound doesn't install at all. It doesn't have incompatible packages - it just dumps me the error log.

I tried your suggestions. I previously did not have boost installed (is that necessary to install this package?), but I installed it and linked it w/ Powershell as described and I think the logs are the same. I ran apm with --verbose and this seems to be the part that's failing according to it:

```
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir C:\Users\erisk\.atom\.node-gyp\.node-gyp\iojs-2.0.18
gyp verb found first Solution file build/binding.sln
gyp verb could not find "msbuild.exe" in PATH - finding location in registry
gyp verb "Release" dir needed to be created? null
gyp verb copying "iojs.lib" for x64 C:\Users\erisk\.atom\.node-gyp\.node-gyp\iojs-2.0.18\Release\iojs.lib
gyp info spawn C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Users\erisk\AppData\Local\Temp\apm-install-dir-119217-5020-1pzyxdo.mp78\node_modules\linter-csound\node_modules\csound-api\build\csound-api.vcxproj(20,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\erisk\AppData\Local\atom\app-1.35.1\resources\app\apm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Users\\erisk\\AppData\\Local\\atom\\app-1.35.1\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\erisk\\AppData\\Local\\atom\\app-1.35.1\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\erisk\AppData\Local\Temp\apm-install-dir-119217-5020-1pzyxdo.mp78\node_modules\linter-csound\node_modules\csound-api
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\erisk\AppData\Local\Temp\apm-install-dir-119217-5020-1pzyxdo.mp78\package.json'
npm WARN apm-install-dir-119217-5020-1pzyxdo.mp78 No description
npm WARN apm-install-dir-119217-5020-1pzyxdo.mp78 No repository field.
npm WARN apm-install-dir-119217-5020-1pzyxdo.mp78 No README data
npm WARN apm-install-dir-119217-5020-1pzyxdo.mp78 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! csound-api@0.10.12 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the csound-api@0.10.12 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\erisk\.atom\.apm\_logs\2019-03-18T01_20_59_156Z-debug.log
```

The other error log (the one spit out at the \_logs path) is nearly identical except that it's now trying to build csound-api@0.10.12 instead of 0.10.10

**Comment by nwhetsell** [comment]
This part—

```
C:\Users\erisk\AppData\Local\Temp\apm-install-dir-119217-5020-1pzyxdo.mp78\node_modules\linter-csound\node_modules\csound-api\build\csound-api.vcxproj(20,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
```

—seems weird to me.

linter-csound depends on [csound-api](https://github.com/nwhetsell/csound-api), which in turn has all the [dependencies](https://github.com/nwhetsell/csound-api#on-windows) of a [Node.js Addon](https://nodejs.org/api/addons.html). Are you able to install csound-api after following the steps at https://github.com/nwhetsell/csound-api#on-windows?

**Comment by bellicapax** [comment]
Thank you!

I followed the instructions on that page (and the instructions it linked to). I installed boost via the installer and installed the 2015 windows-build-tools (following the directions for just using my 2017 vs installation was not working with node-gyp and there's [a pretty big thread about it](https://github.com/nodejs/node-gyp/issues/1144). That finally did it!
