### ISSUE TITLE
linter-csound installation errors

### ISSUE THREAD

**Issue by mmcgilvery** [nwhetsell/linter-csound#2]
Hello. I attempted to install linter-csound and ide-csound and received similar errors for both, but will post the linter-csound one here. I've tried uninstalling and reinstalling csound and that didnt work. I have the latest node and npm.

```
> csound-api@0.10.1 install /private/var/folders/5j/3gqtrn4d6d14fphf215jpkjr0000gn/T/apm-install-dir-117313-20383-1nd8dvz.544hxv42t9/node_modules/linter-csound/node_modules/csound-api
> node-gyp rebuild

  CXX(target) Release/obj.target/csound-api/src/csound-api.o

2017-04-13 11:14:53.829 xcodebuild[20398:3457590] [MT] PluginLoading: Required plug-in compatibility UUID DFFB3951-EB0A-4C09-9DAC-5F2D28CC839C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin' not present in DVTPlugInCompatibilityUUIDs
../src/csound-api.cc:2:10: fatal error: 'csound/cwindow.h' file not found
#include <csound/cwindow.h>
         ^
1 error generated.
make: *** [Release/obj.target/csound-api/src/csound-api.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.5.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /private/var/folders/5j/3gqtrn4d6d14fphf215jpkjr0000gn/T/apm-install-dir-117313-20383-1nd8dvz.544hxv42t9/node_modules/linter-csound/node_modules/csound-api
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/5j/3gqtrn4d6d14fphf215jpkjr0000gn/T/apm-install-dir-117313-20383-1nd8dvz.544hxv42t9/package.json'
npm WARN apm-install-dir-117313-20383-1nd8dvz.544hxv42t9 No description
npm WARN apm-install-dir-117313-20383-1nd8dvz.544hxv42t9 No repository field.
npm WARN apm-install-dir-117313-20383-1nd8dvz.544hxv42t9 No README data
npm WARN apm-install-dir-117313-20383-1nd8dvz.544hxv42t9 No license field.
npm ERR! Darwin 16.5.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/lcukypawn/.atom/.apm/.apmrc" "--userconfig" "/Users/lcukypawn/.atom/.apmrc" "install" "/private/var/folders/5j/3gqtrn4d6d14fphf215jpkjr0000gn/T/d-117313-20383-hfgd9m.n6y99t3xr/package.tgz" "--runtime=electron" "--target=1.3.13" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! csound-api@0.10.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the csound-api@0.10.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the csound-api package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs csound-api
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls csound-api
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/5j/3gqtrn4d6d14fphf215jpkjr0000gn/T/apm-install-dir-117313-20383-1nd8dvz.544hxv42t9/npm-debug.log
```

**Comment by nwhetsell** [comment]
This is saying that Xcode can’t find Csound’s headers on your Mac. Can you look in /usr/local/include and confirm that it contains a folder named csound, and that this csound folder contains cwindow.h? In Finder, you can quickly go to /usr/local/include by pressing <kbd>Command</kbd>-<kbd>Shift</kbd>-<kbd>G</kbd> and entering “/usr/local/include” in the text field that appears.

**If there’s no folder named csound in /usr/local/include…**

…this probably means you’re installing Csound using an installer in a disk image you can download from https://github.com/csound/csound/releases. If so, you can create a symbolic link to Csound’s headers in /usr/local/include by running in Terminal

```sh
ln -s /Library/Frameworks/CsoundLib64.framework/Headers /usr/local/include/csound
```

**If there’s a folder named csound in /usr/local/include…**

…open a Terminal and enter

```sh
c++ -E -x c++ - -v < /dev/null
```

In the output of that, you should see this line:

```
#include <...> search starts here:
```

And, somewhere below that, you should see this line:

```
End of search list.
```

Is `/usr/local/include` somewhere in between those two lines?

**Comment by mmcgilvery** [comment]
/usr/local/include verbatim is not on any of the lines in the second step you've provided. There are some lines that have  usr/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include, but not usr/local/include.

**Comment by mmcgilvery** [comment]
The packages have installed without error messages on Atom with the step 1 correction. Thank you

**Comment by nwhetsell** [comment]
Great, happy to help!
